Jayanth
parth-panchal/cineLog pull request #30
Opened 2023-04-18 03:02 UTC by Djayanth15

Added data files for lists

2023-04-18 04:01 UTC, parshsee requested changes

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    if (!ObjectId.isValid(userId)) throw "invalid object ID";
Lines 16-18, there is already a validation helper to check for IDs. You can replace those three lines with
```suggestion
    userId = validation.checkId(userId, "User ID")
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    title = title.trim();
There is no validation here for the title, you are just trimming it. You could use the validation helper to check if its a string and trim it:
```suggestion
    title = validation.checkString(title, "Title");
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    });
You can create a validation function in validation.js that would check if it is a movie array, then just call the function here:
```suggestion
movies = validation.checkMovieArray(movies, "Movies");
```
Look at the comments in validation.js to see how checkMovieArray should be implemented

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    if (user === null) throw "No user with that id";
Since users data is in develop, you can import the file into here like: `import * as userData from './users.js'` and then replace this line with:
```suggestion
    const user = await usersData.getUserById(userId);
```
and the call will take care of any checks for you

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +      throw "No update occured in the user while adding album!";
Lol, no update occurred in the user while adding album? I think you mean while adding lists yeah?

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    if (!ObjectId.isValid(userId)) throw "invalid object ID";
Same as the first comment, you can use the existing validation function for that:
```suggestion
    userId = validation.checkId(userId, "User ID")
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    if (user === null) throw "No user with that id";
Here too, if you import it, you can use the userData functions to make the DB call and do the validation for you:
```suggestion
    const user = await usersData.getUserById(userId);
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    if (!ObjectId.isValid(listId)) throw "invalid object ID";
Same as the first comment, you can use the existing validation function for that:
```suggestion
    userId = validation.checkId(userId, "User ID")
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    // console.log("hi3");
Same as the first comment, you can use the existing validation function for that:
```suggestion
    listId= validation.checkId(listId, "ListID")
```

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    // console.log(userCollection)
Remove the console log statements, if you're done using them.

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    // console.log(r);
Remove the console log statements and anything commented out, if you're done using them.

2023-04-18 04:01 UTC, parshsee commented on data/lists.js
> +    });
Same validation changes as in the create function

2023-04-18 04:01 UTC, parshsee commented on utils/validation.js
> +
This is the same as the checkString function above it. You can delete this.

2023-04-18 04:01 UTC, parshsee commented on utils/validation.js
> +
You can create a validation function to check the movie array parameter in create and update. The function would look like this: 
```suggestion
const checkMovieArray = (arr, name) => {
  if (!Array.isArray(arr)) throw `Error: ${name} must be an array`;

  if (arr.length === 0) throw `Error: ${name} must have at least one element`;

  for (let index in arr) {
    arr[index] = checkMovieId(arr[index]);
  }

  return arr;
}
```

Be sure to export it too

2023-04-18 04:01 UTC, parshsee commented on utils/validation.js
> +import { getMovieInfo } from "../utils/helper.js";
Why is this here twice? Can you check to see if its like that on your local and delete one if there is two?

2023-04-18 04:01 UTC, parshsee commented on utils/helper.js
> +import * as dotenv from "dotenv";
Can you go through this file and check why there seems to be some lines of the same code appearing twice?

2023-04-18 18:29 UTC, Djayanth15 commented
I have made the necessary changes that you suggested

2023-04-18 21:39 UTC, parshsee requested changes

2023-04-18 21:39 UTC, parshsee commented on data/lists.js
> +    userId = validation.checkId(userId, "User ID")
This should be listId, not userId

2023-04-19 02:08 UTC, parshsee approved these changes

2023-04-19 02:09 UTC, merged